# Generated by Django 3.2.9 on 2021-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
