# Generated by Django 3.2.9 on 2021-11-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_post_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='post',
        ),
    ]
