# Generated by Django 3.2.9 on 2021-11-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('video_path', models.CharField(max_length=200)),
                ('genres', models.ManyToManyField(related_name='eventmovie', to='movies.Genre')),
            ],
        ),
    ]
